version: '3'

volumes:
  mysql-data:
  myadmin-data:
  redis-data:

services:
   # PHP 7.3 (with Nginx)
  app:
    container_name: admin-app
    build: ./devops/environments/development/dockerfiles/app
    volumes:
      - ./project:/var/www/app
    ports:
      - "80:8080"
    depends_on:
      - mysql
      - redis
      - queue

  # Front NodeJS
  front:
    container_name: admin-front
    build: ./devops/environments/development/dockerfiles/front
    tty: true
    volumes:
      - ./project:/var/www/app
    depends_on:
      - app

  # Database - Mysql (11)
  mysql:
    container_name: admin-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=admin

  # Adminer mysql
  phpmyadmin:
    container_name: admin-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5001:80
    volumes:
      - myadmin-data:/var/lib/phpmyadmin
    depends_on:
      - mysql

  # MailHog - Fake SMTP server.
  mailhog:
    container_name: admin-mailhog
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'  # Port 1025 => SMTP.
      - '8025:8025'  # Port 8025 => Web dashboard (http://127.0.0.1:8025).

  # Queue Worker
  queue:
    image: ambientum/php:7.3
    container_name: admin-queue
    volumes:
      - ./project:/var/www/app
    command: php artisan horizon
    restart: unless-stopped
    depends_on:
      - mysql
      - redis

  # Redis cache
  redis:
    container_name: admin-redis
    image: redis:5.0-alpine
    restart: always
    volumes:
      - 'redis-data:/data'
    ports:
      - 6379:6379